### ISSUE TITLE
Trigger CI release process for new Electron versions

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/mist-shell#2]
We want the CI to build a new release draft whenever a new Electron version is released to:
https://github.com/electron/electron/releases

After the build is tested and changed from `draft` to `release` this should also trigger the auto-updater so that installed version automatically update.

**Comment by evertonfraga** [comment]
Should we release a new shell for every electron `minor` bump, or does a `patch` also apply?

**Comment by PhilippLgh** [comment]
We should probably build for minor and patch versions to have the latest version linked to on the download page and shipped. However, not every release should necessarily trigger the auto-updater of already installed versions

**Comment by evertonfraga** [comment]
Here I implemented Renovate, and whitelisted only `electron` package. It requires human interaction for merging it (which I believe is better than a fully automatic solution).

Renovate creates a PR for each new electron version (example here: https://github.com/ethereum/mist-shell/pull/13)
